#ifndef DETECT_BUILTINS_H
#define DETECT_BUILTINS_H

#include <stdbool.h>
#include <mpi.h>

#define DT_ELIF(type) \
    else if (type_c == (type)) { \
        return true; \
    }

MAYBE_UNUSED
static bool C_MPI_TYPE_IS_BUILTIN(MPI_Datatype type_c)
{
    if (false) { return false; }
    DT_ELIF(MPI_CHARACTER)
    DT_ELIF(MPI_LOGICAL)
    DT_ELIF(MPI_INTEGER)
    DT_ELIF(MPI_REAL)
    DT_ELIF(MPI_DOUBLE_PRECISION)
    DT_ELIF(MPI_COMPLEX)
    DT_ELIF(MPI_DOUBLE_COMPLEX)
    DT_ELIF(MPI_INTEGER1)
    DT_ELIF(MPI_INTEGER2)
    DT_ELIF(MPI_INTEGER4)
    DT_ELIF(MPI_INTEGER8)
#ifdef HAVE_MPI_INTEGER16
    DT_ELIF(MPI_INTEGER16)
#endif
#ifdef HAVE_MPI_REAL2
    DT_ELIF(MPI_REAL2)
#endif
    DT_ELIF(MPI_REAL4)
    DT_ELIF(MPI_REAL8)
#ifdef HAVE_MPI_REAL16
    DT_ELIF(MPI_REAL16)
#endif
#ifdef HAVE_MPI_COMPLEX4
    DT_ELIF(MPI_COMPLEX4)
#endif
    DT_ELIF(MPI_COMPLEX8)
    DT_ELIF(MPI_COMPLEX16)
#ifdef HAVE_MPI_COMPLEX32
    DT_ELIF(MPI_COMPLEX32)
#endif
    DT_ELIF(MPI_AINT)
    DT_ELIF(MPI_COUNT)
    DT_ELIF(MPI_OFFSET)
    DT_ELIF(MPI_BYTE)
    DT_ELIF(MPI_CHAR)
    DT_ELIF(MPI_UNSIGNED_CHAR)
    DT_ELIF(MPI_SIGNED_CHAR)
    DT_ELIF(MPI_WCHAR)
    DT_ELIF(MPI_SHORT)
    DT_ELIF(MPI_UNSIGNED_SHORT)
    DT_ELIF(MPI_INT)
    DT_ELIF(MPI_LONG)
    DT_ELIF(MPI_UNSIGNED)
    DT_ELIF(MPI_UNSIGNED_LONG)
    DT_ELIF(MPI_LONG_LONG_INT)
    DT_ELIF(MPI_UNSIGNED_LONG_LONG)
    DT_ELIF(MPI_FLOAT)
    DT_ELIF(MPI_DOUBLE)
    DT_ELIF(MPI_LONG_DOUBLE)
    DT_ELIF(MPI_C_BOOL)
    DT_ELIF(MPI_INT8_T)
    DT_ELIF(MPI_INT16_T)
    DT_ELIF(MPI_INT32_T)
    DT_ELIF(MPI_INT64_T)
    DT_ELIF(MPI_UINT8_T)
    DT_ELIF(MPI_UINT16_T)
    DT_ELIF(MPI_UINT32_T)
    DT_ELIF(MPI_UINT64_T)
    DT_ELIF(MPI_C_COMPLEX)
    DT_ELIF(MPI_C_FLOAT_COMPLEX)
    DT_ELIF(MPI_C_DOUBLE_COMPLEX)
    DT_ELIF(MPI_C_LONG_DOUBLE_COMPLEX)
    return false;
}

#undef DT_ELIF

#define OP_ELIF(op) \
    else if (op_c == (op)) { \
        return true; \
    }

MAYBE_UNUSED
static bool C_MPI_OP_IS_BUILTIN(MPI_Op op_c)
{
    if (false) { return false; }
    OP_ELIF(MPI_MAX)
    OP_ELIF(MPI_MIN)
    OP_ELIF(MPI_SUM)
    OP_ELIF(MPI_PROD)
    OP_ELIF(MPI_MAXLOC)
    OP_ELIF(MPI_MINLOC)
    OP_ELIF(MPI_BAND)
    OP_ELIF(MPI_BOR)
    OP_ELIF(MPI_BXOR)
    OP_ELIF(MPI_LAND)
    OP_ELIF(MPI_LOR)
    OP_ELIF(MPI_LXOR)
    return false;
}

#undef OP_ELIF

#endif // DETECT_BUILTINS_H
