module mpi_f08
    use mpi_handle_types
    use mpi_handle_operators
    use mpi_global_constants
    use mpi_core_f
    use mpi_coll_f
    use mpi_comm_f
    use mpi_datatype_f
    use mpi_file_f
    use mpi_group_f
    use mpi_info_f
    use mpi_message_f
    use mpi_p2p_f
    use mpi_op_f
    use mpi_request_f
    use mpi_status_f
    use mpi_rma_f
    use mpi_win_f
    use mpi_attr_f
    use mpi_error_f
end module mpi_f08
