#define TNAME f08_op_t_0
#define TSLOT 0
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_1
#define TSLOT 1
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_2
#define TSLOT 2
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_3
#define TSLOT 3
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_4
#define TSLOT 4
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_5
#define TSLOT 5
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_6
#define TSLOT 6
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_7
#define TSLOT 7
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_8
#define TSLOT 8
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_9
#define TSLOT 9
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_10
#define TSLOT 10
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_11
#define TSLOT 11
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_12
#define TSLOT 12
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_13
#define TSLOT 13
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_14
#define TSLOT 14
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_15
#define TSLOT 15
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_16
#define TSLOT 16
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_17
#define TSLOT 17
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_18
#define TSLOT 18
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_19
#define TSLOT 19
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_20
#define TSLOT 20
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_21
#define TSLOT 21
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_22
#define TSLOT 22
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_23
#define TSLOT 23
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_24
#define TSLOT 24
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_25
#define TSLOT 25
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_26
#define TSLOT 26
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_27
#define TSLOT 27
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_28
#define TSLOT 28
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_29
#define TSLOT 29
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_30
#define TSLOT 30
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_31
#define TSLOT 31
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_32
#define TSLOT 32
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_33
#define TSLOT 33
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_34
#define TSLOT 34
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_35
#define TSLOT 35
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_36
#define TSLOT 36
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_37
#define TSLOT 37
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_38
#define TSLOT 38
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_39
#define TSLOT 39
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_40
#define TSLOT 40
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_41
#define TSLOT 41
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_42
#define TSLOT 42
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_43
#define TSLOT 43
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_44
#define TSLOT 44
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_45
#define TSLOT 45
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_46
#define TSLOT 46
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_47
#define TSLOT 47
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_48
#define TSLOT 48
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_49
#define TSLOT 49
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_50
#define TSLOT 50
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_51
#define TSLOT 51
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_52
#define TSLOT 52
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_53
#define TSLOT 53
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_54
#define TSLOT 54
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_55
#define TSLOT 55
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_56
#define TSLOT 56
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_57
#define TSLOT 57
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_58
#define TSLOT 58
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_59
#define TSLOT 59
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_60
#define TSLOT 60
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_61
#define TSLOT 61
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_62
#define TSLOT 62
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT

#define TNAME f08_op_t_63
#define TSLOT 63
#include "mpi_op_trampoline_template.inc"
#undef TNAME
#undef TSLOT
