#ifndef VAPAA_CONSTANTS_H
#define VAPAA_CONSTANTS_H

#define VAPAA_MPI_THREAD_SINGLE        0
#define VAPAA_MPI_THREAD_FUNNELED   1024
#define VAPAA_MPI_THREAD_SERIALIZED 2048
#define VAPAA_MPI_THREAD_MULTIPLE   4096

#define VAPAA_MPI_IDENT     201
#define VAPAA_MPI_CONGRUENT 202
#define VAPAA_MPI_SIMILAR   203
#define VAPAA_MPI_UNEQUAL   204

#define VAPAA_MPI_COMM_NULL        256
#define VAPAA_MPI_COMM_WORLD       257
#define VAPAA_MPI_COMM_SELF        258

#define VAPAA_MPI_GROUP_NULL       264
#define VAPAA_MPI_GROUP_EMPTY      265

#define VAPAA_MPI_WIN_NULL         272

#define VAPAA_MPI_FILE_NULL        280

#define VAPAA_MPI_SESSION_NULL     288

#define VAPAA_MPI_MESSAGE_NULL     296
#define VAPAA_MPI_MESSAGE_NO_PROC  297

#define VAPAA_MPI_INFO_NULL        304
#define VAPAA_MPI_INFO_ENV         305

#define VAPAA_MPI_ERRHANDLER_NULL  320
#define VAPAA_MPI_ERRORS_ARE_FATAL 321
#define VAPAA_MPI_ERRORS_ABORT     322
#define VAPAA_MPI_ERRORS_RETURN    323

#define VAPAA_MPI_OP_NULL          32

#define VAPAA_MPI_REQUEST_NULL     384

#define VAPAA_MPI_DATATYPE_NULL    512

#define VAPAA_MPI_ANY_SOURCE       (-1)
#define VAPAA_MPI_ANY_TAG          (-2)
#define VAPAA_MPI_PROC_NULL        (-3)
#define VAPAA_MPI_ROOT             (-4)

#define VAPAA_MPI_UNDEFINED        (-32766)

#define VAPAA_MPI_ORDER_C          12
#define VAPAA_MPI_ORDER_FORTRAN    15

#define VAPAA_MPI_DISTRIBUTE_NONE       16
#define VAPAA_MPI_DISTRIBUTE_BLOCK      17
#define VAPAA_MPI_DISTRIBUTE_CYCLIC     18
#define VAPAA_MPI_DISTRIBUTE_DFLT_DARG  19

#define VAPAA_MPI_COMBINER_NAMED          101
#define VAPAA_MPI_COMBINER_DUP            102
#define VAPAA_MPI_COMBINER_CONTIGUOUS     103
#define VAPAA_MPI_COMBINER_VECTOR         104
#define VAPAA_MPI_COMBINER_HVECTOR        105
#define VAPAA_MPI_COMBINER_INDEXED        106
#define VAPAA_MPI_COMBINER_HINDEXED       107
#define VAPAA_MPI_COMBINER_INDEXED_BLOCK  108
#define VAPAA_MPI_COMBINER_HINDEXED_BLOCK 109
#define VAPAA_MPI_COMBINER_STRUCT         110
#define VAPAA_MPI_COMBINER_SUBARRAY       111
#define VAPAA_MPI_COMBINER_DARRAY         112
#define VAPAA_MPI_COMBINER_F90_REAL       113
#define VAPAA_MPI_COMBINER_F90_COMPLEX    114
#define VAPAA_MPI_COMBINER_F90_INTEGER    115
#define VAPAA_MPI_COMBINER_RESIZED        116
#define VAPAA_MPI_COMBINER_VALUE_INDEX    117

#define VAPAA_MPI_TYPECLASS_INTEGER  192
#define VAPAA_MPI_TYPECLASS_REAL     193
#define VAPAA_MPI_TYPECLASS_COMPLEX  194

#define VAPAA_MPI_CART       211
#define VAPAA_MPI_GRAPH      212
#define VAPAA_MPI_DIST_GRAPH 213

#define VAPAA_MPI_COMM_TYPE_SHARED           221
#define VAPAA_MPI_COMM_TYPE_HW_UNGUIDED      222
#define VAPAA_MPI_COMM_TYPE_HW_GUIDED        223
#define VAPAA_MPI_COMM_TYPE_RESOURCE_GUIDED  224

#define VAPAA_MPI_MAX_PROCESSOR_NAME          256
#define VAPAA_MPI_MAX_LIBRARY_VERSION_STRING 8192
#define VAPAA_MPI_MAX_ERROR_STRING            512
#define VAPAA_MPI_MAX_DATAREP_STRING          128
#define VAPAA_MPI_MAX_INFO_KEY                256
#define VAPAA_MPI_MAX_INFO_VAL               1024
#define VAPAA_MPI_MAX_OBJECT_NAME             128
#define VAPAA_MPI_MAX_PORT_NAME              1024
#define VAPAA_MPI_MAX_STRINGTAG_LEN          1024
#define VAPAA_MPI_MAX_PSET_NAME_LEN          1024

#define VAPAA_MPI_BSEND_OVERHEAD  512

#define VAPAA_MPI_DISPLACEMENT_CURRENT  (-1)

#define VAPAA_MPI_SUM        33
#define VAPAA_MPI_MIN        34
#define VAPAA_MPI_MAX        35
#define VAPAA_MPI_PROD       36
#define VAPAA_MPI_BAND       40
#define VAPAA_MPI_BOR        41
#define VAPAA_MPI_BXOR       42
#define VAPAA_MPI_LAND       48
#define VAPAA_MPI_LOR        49
#define VAPAA_MPI_LXOR       50
#define VAPAA_MPI_MINLOC     56
#define VAPAA_MPI_MAXLOC     57
#define VAPAA_MPI_REPLACE    60
#define VAPAA_MPI_NO_OP      61

#define VAPAA_MPI_CHARACTER          542
#define VAPAA_MPI_LOGICAL            536
#define VAPAA_MPI_INTEGER            537
#define VAPAA_MPI_REAL               538
#define VAPAA_MPI_DOUBLE_PRECISION   540
#define VAPAA_MPI_COMPLEX            539
#define VAPAA_MPI_DOUBLE_COMPLEX     541

#define VAPAA_MPI_LOGICAL1           704
#define VAPAA_MPI_INTEGER1           705
#define VAPAA_MPI_LOGICAL2           712
#define VAPAA_MPI_INTEGER2           713
#define VAPAA_MPI_REAL2              714
#define VAPAA_MPI_LOGICAL4           720
#define VAPAA_MPI_INTEGER4           721
#define VAPAA_MPI_REAL4              722
#define VAPAA_MPI_COMPLEX4           723
#define VAPAA_MPI_LOGICAL8           728
#define VAPAA_MPI_INTEGER8           729
#define VAPAA_MPI_REAL8              730
#define VAPAA_MPI_COMPLEX8           731
#define VAPAA_MPI_LOGICAL16          736
#define VAPAA_MPI_INTEGER16          737
#define VAPAA_MPI_REAL16             738
#define VAPAA_MPI_COMPLEX16          739
#define VAPAA_MPI_COMPLEX32          747

#define VAPAA_MPI_AINT               513
#define VAPAA_MPI_COUNT              514
#define VAPAA_MPI_OFFSET             515
#define VAPAA_MPI_PACKED             519

#define VAPAA_MPI_CHAR               579
#define VAPAA_MPI_SIGNED_CHAR        580
#define VAPAA_MPI_UNSIGNED_CHAR      581
#define VAPAA_MPI_BYTE               583
#define VAPAA_MPI_WCHAR              572
#define VAPAA_MPI_SHORT              520
#define VAPAA_MPI_UNSIGNED_SHORT     524
#define VAPAA_MPI_INT                521
#define VAPAA_MPI_UNSIGNED           525
#define VAPAA_MPI_LONG               522
#define VAPAA_MPI_UNSIGNED_LONG      526
#define VAPAA_MPI_LONG_LONG          523
#define VAPAA_MPI_LONG_LONG_INT      VAPAA_MPI_LONG_LONG
#define VAPAA_MPI_UNSIGNED_LONG_LONG 527
#define VAPAA_MPI_FLOAT              528
#define VAPAA_MPI_DOUBLE             532
#define VAPAA_MPI_LONG_DOUBLE        544

#define VAPAA_MPI_C_BOOL                568
#define VAPAA_MPI_C_FLOAT_COMPLEX       530
#define VAPAA_MPI_C_COMPLEX             VAPAA_MPI_C_FLOAT_COMPLEX
#define VAPAA_MPI_CXX_FLOAT_COMPLEX     531
#define VAPAA_MPI_C_DOUBLE_COMPLEX      534
#define VAPAA_MPI_CXX_DOUBLE_COMPLEX    535
#define VAPAA_MPI_C_LONG_DOUBLE_COMPLEX 548
#define VAPAA_MPI_CXX_LONG_DOUBLE_COMPLEX 549
#define VAPAA_MPI_CXX_BOOL              569

#define VAPAA_MPI_INT8_T             576
#define VAPAA_MPI_UINT8_T            577
#define VAPAA_MPI_INT16_T            584
#define VAPAA_MPI_UINT16_T           585
#define VAPAA_MPI_INT32_T            592
#define VAPAA_MPI_UINT32_T           593
#define VAPAA_MPI_INT64_T            600
#define VAPAA_MPI_UINT64_T           601

#define VAPAA_MPI_FLOAT_INT          552
#define VAPAA_MPI_DOUBLE_INT         553
#define VAPAA_MPI_LONG_INT           554
#define VAPAA_MPI_2INT               555
#define VAPAA_MPI_SHORT_INT          556
#define VAPAA_MPI_LONG_DOUBLE_INT    557

#define VAPAA_MPI_2REAL              560
#define VAPAA_MPI_2DOUBLE_PRECISION  561
#define VAPAA_MPI_2INTEGER           562

#define VAPAA_MPI_SUCCESS                     0
#define VAPAA_MPI_ERR_BUFFER                  1
#define VAPAA_MPI_ERR_COUNT                   2
#define VAPAA_MPI_ERR_TYPE                    3
#define VAPAA_MPI_ERR_TAG                     4
#define VAPAA_MPI_ERR_COMM                    5
#define VAPAA_MPI_ERR_RANK                    6
#define VAPAA_MPI_ERR_REQUEST                 7
#define VAPAA_MPI_ERR_ROOT                    8
#define VAPAA_MPI_ERR_GROUP                   9
#define VAPAA_MPI_ERR_OP                     10
#define VAPAA_MPI_ERR_TOPOLOGY               11
#define VAPAA_MPI_ERR_DIMS                   12
#define VAPAA_MPI_ERR_ARG                    13
#define VAPAA_MPI_ERR_UNKNOWN                14
#define VAPAA_MPI_ERR_TRUNCATE               15
#define VAPAA_MPI_ERR_OTHER                  16
#define VAPAA_MPI_ERR_INTERN                 17
#define VAPAA_MPI_ERR_PENDING                18
#define VAPAA_MPI_ERR_IN_STATUS              19
#define VAPAA_MPI_ERR_ACCESS                 20
#define VAPAA_MPI_ERR_AMODE                  21
#define VAPAA_MPI_ERR_ASSERT                 22
#define VAPAA_MPI_ERR_BAD_FILE               23
#define VAPAA_MPI_ERR_BASE                   24
#define VAPAA_MPI_ERR_CONVERSION             25
#define VAPAA_MPI_ERR_DISP                   26
#define VAPAA_MPI_ERR_DUP_DATAREP            27
#define VAPAA_MPI_ERR_FILE_EXISTS            28
#define VAPAA_MPI_ERR_FILE_IN_USE            29
#define VAPAA_MPI_ERR_FILE                   30
#define VAPAA_MPI_ERR_INFO_KEY               31
#define VAPAA_MPI_ERR_INFO_NOKEY             32
#define VAPAA_MPI_ERR_INFO_VALUE             33
#define VAPAA_MPI_ERR_INFO                   34
#define VAPAA_MPI_ERR_IO                     35
#define VAPAA_MPI_ERR_KEYVAL                 36
#define VAPAA_MPI_ERR_LOCKTYPE               37
#define VAPAA_MPI_ERR_NAME                   38
#define VAPAA_MPI_ERR_NO_MEM                 39
#define VAPAA_MPI_ERR_NOT_SAME               40
#define VAPAA_MPI_ERR_NO_SPACE               41
#define VAPAA_MPI_ERR_NO_SUCH_FILE           42
#define VAPAA_MPI_ERR_PORT                   43
#define VAPAA_MPI_ERR_QUOTA                  44
#define VAPAA_MPI_ERR_READ_ONLY              45
#define VAPAA_MPI_ERR_RMA_ATTACH             46
#define VAPAA_MPI_ERR_RMA_CONFLICT           47
#define VAPAA_MPI_ERR_RMA_RANGE              48
#define VAPAA_MPI_ERR_RMA_SHARED             49
#define VAPAA_MPI_ERR_RMA_SYNC               50
#define VAPAA_MPI_ERR_SERVICE                51
#define VAPAA_MPI_ERR_SIZE                   52
#define VAPAA_MPI_ERR_SPAWN                  53
#define VAPAA_MPI_ERR_UNSUPPORTED_DATAREP    54
#define VAPAA_MPI_ERR_UNSUPPORTED_OPERATION  55
#define VAPAA_MPI_ERR_WIN                    56
#define VAPAA_MPI_ERR_RMA_FLAVOR             57
#define VAPAA_MPI_ERR_PROC_ABORTED           58
#define VAPAA_MPI_ERR_VALUE_TOO_LARGE        59
#define VAPAA_MPI_ERR_SESSION                60
#define VAPAA_MPI_ERR_ERRHANDLER             61
#define VAPAA_MPI_ERR_ABI                    62
#define VAPAA_MPI_ERR_LASTCODE           16383

#define VAPAA_MPI_T_ERR_CANNOT_INIT       1001
#define VAPAA_MPI_T_ERR_NOT_ACCESSIBLE    1002
#define VAPAA_MPI_T_ERR_NOT_INITIALIZED   1003
#define VAPAA_MPI_T_ERR_NOT_SUPPORTED     1004
#define VAPAA_MPI_T_ERR_MEMORY            1005
#define VAPAA_MPI_T_ERR_INVALID           1006
#define VAPAA_MPI_T_ERR_INVALID_INDEX     1007
#define VAPAA_MPI_T_ERR_INVALID_ITEM      1008
#define VAPAA_MPI_T_ERR_INVALID_SESSION   1009
#define VAPAA_MPI_T_ERR_INVALID_HANDLE    1010
#define VAPAA_MPI_T_ERR_INVALID_NAME      1011
#define VAPAA_MPI_T_ERR_OUT_OF_HANDLES    1012
#define VAPAA_MPI_T_ERR_OUT_OF_SESSIONS   1013
#define VAPAA_MPI_T_ERR_CVAR_SET_NOT_NOW  1014
#define VAPAA_MPI_T_ERR_CVAR_SET_NEVER    1015
#define VAPAA_MPI_T_ERR_PVAR_NO_WRITE     1016
#define VAPAA_MPI_T_ERR_PVAR_NO_STARTSTOP 1017
#define VAPAA_MPI_T_ERR_PVAR_NO_ATOMIC    1018

#define VAPAA_MPI_MODE_APPEND             1
#define VAPAA_MPI_MODE_CREATE             2
#define VAPAA_MPI_MODE_DELETE_ON_CLOSE    4
#define VAPAA_MPI_MODE_EXCL               8
#define VAPAA_MPI_MODE_RDONLY            16
#define VAPAA_MPI_MODE_RDWR              32
#define VAPAA_MPI_MODE_SEQUENTIAL        64
#define VAPAA_MPI_MODE_UNIQUE_OPEN      128
#define VAPAA_MPI_MODE_WRONLY           256

#define VAPAA_MPI_MODE_NOCHECK         1024
#define VAPAA_MPI_MODE_NOPRECEDE       2048
#define VAPAA_MPI_MODE_NOPUT           4096
#define VAPAA_MPI_MODE_NOSTORE         8192
#define VAPAA_MPI_MODE_NOSUCCEED      16384

#define VAPAA_MPI_SEEK_CUR  401
#define VAPAA_MPI_SEEK_END  402
#define VAPAA_MPI_SEEK_SET  403

#define VAPAA_MPI_WIN_FLAVOR_CREATE    311
#define VAPAA_MPI_WIN_FLAVOR_ALLOCATE  312
#define VAPAA_MPI_WIN_FLAVOR_DYNAMIC   313
#define VAPAA_MPI_WIN_FLAVOR_SHARED    314

#define VAPAA_MPI_WIN_UNIFIED          321
#define VAPAA_MPI_WIN_SEPARATE         322

#define VAPAA_MPI_LOCK_EXCLUSIVE       301
#define VAPAA_MPI_LOCK_SHARED          302

#define VAPAA_MPI_KEYVAL_INVALID         0

#define VAPAA_MPI_TAG_UB               501
#define VAPAA_MPI_IO                   502
#define VAPAA_MPI_HOST                 503
#define VAPAA_MPI_WTIME_IS_GLOBAL      504
#define VAPAA_MPI_APPNUM               505
#define VAPAA_MPI_LASTUSEDCODE         506
#define VAPAA_MPI_UNIVERSE_SIZE        507

#define VAPAA_MPI_WIN_BASE          601
#define VAPAA_MPI_WIN_DISP_UNIT     602
#define VAPAA_MPI_WIN_SIZE          603
#define VAPAA_MPI_WIN_CREATE_FLAVOR 604
#define VAPAA_MPI_WIN_MODEL         605

#define VAPAA_MPI_T_CB_REQUIRE_NONE              0
#define VAPAA_MPI_T_CB_REQUIRE_MPI_RESTRICTED    3
#define VAPAA_MPI_T_CB_REQUIRE_THREAD_SAFE      15
#define VAPAA_MPI_T_CB_REQUIRE_ASYNC_SIGNAL_SAFE 63

#define VAPAA_MPI_T_SOURCE_ORDERED   1
#define VAPAA_MPI_T_SOURCE_UNORDERED 2

#define VAPAA_MPI_T_VERBOSITY_USER_BASIC    9
#define VAPAA_MPI_T_VERBOSITY_USER_DETAIL  10
#define VAPAA_MPI_T_VERBOSITY_USER_ALL     12
#define VAPAA_MPI_T_VERBOSITY_TUNER_BASIC  17
#define VAPAA_MPI_T_VERBOSITY_TUNER_DETAIL 18
#define VAPAA_MPI_T_VERBOSITY_TUNER_ALL    20
#define VAPAA_MPI_T_VERBOSITY_MPIDEV_BASIC  33
#define VAPAA_MPI_T_VERBOSITY_MPIDEV_DETAIL 34
#define VAPAA_MPI_T_VERBOSITY_MPIDEV_ALL    36

#define VAPAA_MPI_T_BIND_NO_OBJECT    1
#define VAPAA_MPI_T_BIND_MPI_COMM     2
#define VAPAA_MPI_T_BIND_MPI_DATATYPE 3
#define VAPAA_MPI_T_BIND_MPI_ERRHANDLER 4
#define VAPAA_MPI_T_BIND_MPI_FILE     5
#define VAPAA_MPI_T_BIND_MPI_GROUP    6
#define VAPAA_MPI_T_BIND_MPI_OP       7
#define VAPAA_MPI_T_BIND_MPI_REQUEST  8
#define VAPAA_MPI_T_BIND_MPI_WIN      9
#define VAPAA_MPI_T_BIND_MPI_MESSAGE  10
#define VAPAA_MPI_T_BIND_MPI_INFO     11
#define VAPAA_MPI_T_BIND_MPI_SESSION  12

#define VAPAA_MPI_T_SCOPE_CONSTANT  1
#define VAPAA_MPI_T_SCOPE_READONLY  2
#define VAPAA_MPI_T_SCOPE_LOCAL     3
#define VAPAA_MPI_T_SCOPE_GROUP     4
#define VAPAA_MPI_T_SCOPE_GROUP_EQ  5
#define VAPAA_MPI_T_SCOPE_ALL       6
#define VAPAA_MPI_T_SCOPE_ALL_EQ    7

#define VAPAA_MPI_T_PVAR_CLASS_STATE        1
#define VAPAA_MPI_T_PVAR_CLASS_LEVEL        2
#define VAPAA_MPI_T_PVAR_CLASS_SIZE         3
#define VAPAA_MPI_T_PVAR_CLASS_PERCENTAGE   4
#define VAPAA_MPI_T_PVAR_CLASS_HIGHWATERMARK 5
#define VAPAA_MPI_T_PVAR_CLASS_LOWWATERMARK 6
#define VAPAA_MPI_T_PVAR_CLASS_COUNTER      7
#define VAPAA_MPI_T_PVAR_CLASS_AGGREGATE    8
#define VAPAA_MPI_T_PVAR_CLASS_TIMER        9
#define VAPAA_MPI_T_PVAR_CLASS_GENERIC      10

#endif
